springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

# log config
debug: false
logging:
  level:
    com.akofood.server: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
spring:
  # application name config
  application:
    name: server

  # db config
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # jpa config
  jpa:
    defer-datasource-initialization: true
    # for dev
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 1000

  # use data.sql file for dummy data
  sql.init.mode: always


# cors config
cors:
  allowed-origin-frontend-dev: ${ALLOWED_ORIGIN_FRONTEND_DEV}
  allowed-origin-backend-dev: ${ALLOWED_ORIGIN_BACKEND_DEV}
  allowed-origin-deploy: ${ALLOWED_ORIGIN_DEPLOY}